// <auto-generated />
namespace giaiphuongtrinh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Khachhangdb_Duy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Khachhangdb_Duy));
        
        string IMigrationMetadata.Id
        {
            get { return "202109210312296_Khachhangdb_Duy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
